* How your brain makes Decisions

Source: https://www.inc.com/suzanne-lucas/your-brain-is-lying-to-you-heres-how-to-force-it-to-tell-truth.html

We rely too heavily on the first piece of information seen, this is
known as the /anchoring bias/. During decision making, anchoring occurs
when initial piece of information used to make /subsequent judgements/.

The /availability heuristic/, also known as the availability bias, is a
mental shortcut that relies on the immediate examples that comes to a
given person's mind when evaluating a specific topic, concept, method or
decision. This will often give you low-quality information to make your
decision.

- Tendency of remember our choice supportive bias as being better than
  they actually were.
- The clustering illusion bias is where our brain makes us think we see
  a pattern in /random events/, when in reality no pattern exist. Our
  brain just makes one up for us.
- Another one is the confirmation bias, which is essentially filtering
  through data and picking out the information that confirms your
  belief/choice.

Cognitive error that can have a positive effect is the placebo effect,
which is essentially your mind giving the illusion to itself that
something is true, which is actually not. Such as when you tell yourself
that you're not feeling well, you'll start to feel ill or sick in some
way.

selective perception, overlaps somewhat with confirmation bias, tendency
to not notice or ignore things that cause us discomfort. You'll perceive
only the things you want to. This can lead to things, like who you date,
who your friends are, because you choose to ignore very important
information, while over-compensating the small things. Are they really
who you think they are, or are they just who you want them to be in your
head? This goes even further when it comes to yourself, and how you
perceive your own-self. We're certainly not looking for things to
contradict others.
