* The Science of Time Perception: Stop It Slipping Away by Doing New
Things
  :PROPERTIES:
  :CUSTOM_ID: the-science-of-time-perception-stop-it-slipping-away-by-doing-new-things
  :END:

You may notice, if you reflect back into the past, some experiences may
of seemed like they lasted a long time, but why is that? Well it could
have been because you were doing something new, you were having a
completely new experience which you never had before. When this happens
you become so far engaged in that thing, that your perception of time
slows down. (See [[file:20200724211242-perception.org][Perception]])

#+BEGIN_QUOTE
  Yet "brain time," as Eagleman calls it, is intrinsically subjective.
  "Try this exercise," he suggests in a recent essay. "Put this book
  down and go look in a mirror. Now move your eyes back and forth, so
  that >you're looking at your left eye, then at your right eye, then at
  your left eye again. When your eyes shift from one position to the
  other, they take time to move and land on the other location. But
  here's the >kicker: you never see your eyes move." There's no evidence
  of any gaps in your perception---no darkened stretches like bits of
  blank film---yet much of what you see has been edited out. Your brain
  has taken a >complicated scene of eyes darting back and forth and
  recut it as a simple one: your eyes stare straight ahead. Where did
  the missing moments go?
#+END_QUOTE

The author goes on to explain, essentially our perception of time, is a
collection of senses that our brain then organizes in a way that makes
sense to us, before we ever perceive it. So what we /THINK/ is our sense
of time, is actually just a bunch of data presented to us in a
particular way, as determined by our brain.

#+BEGIN_QUOTE
  When our brains receive new information, it doesn't necessarily come
  in the proper order. This information needs to be reorganized and
  presented to us in a form we understand. When familiar information is
  >processed, this doesn't take much time at all. New information,
  however, is a bit slower and makes time feel elongated.
#+END_QUOTE

Unlike our other senses, time is processed by multiple areas of the
brain, and depending on the amount of data, it can take our brain quite
some time to process all that data, hence the longer it takes to process
that data, the longer time feels. (See Cerebral cortex, Basal ganglia
and Cerebellum)

#+BEGIN_QUOTE
  When we're in life-threatening situations, for instance, "we remember
  the time as longer because we record more of the experience.
  Life-threatening experiences make us really pay attention, but we
  don't gain >superhuman powers of perception." The same thing happens
  when we hear enjoyable music, because “greater attention leads to
  perception of a longer period of time.
#+END_QUOTE

So ultimately, if your brain does not have to process a lot of new
information, then time appears to slip by faster and time is processed
more quickly.

#+BEGIN_QUOTE
  The more detailed the memory, the longer the moment seems to last.
  "This explains why we think that time speeds up when we grow older,"
  Eagleman said---why childhood summers seem to go on forever, while old
  age slips by while we're dozing. The more familiar the world becomes,
  the less information your brain writes down, and the more quickly time
  seems to pass.
#+END_QUOTE

#+BEGIN_QUOTE
  "Time is this rubbery thing," Eagleman said. "It stretches out when
  you really turn your brain resources on, and when you say, 'Oh, I got
  this, everything is as expected,' it shrinks up."
#+END_QUOTE

#+BEGIN_QUOTE
  The best example of this is the so-called oddball effect---an optical
  illusion that Eagleman had shown me in his lab. It consisted of a
  series of simple images flashing on a computer screen. Most of the
  time, the >same picture was repeated again and again: a plain brown
  shoe. But every so often a flower would appear instead. To my mind,
  the change was a matter of timing as well as of content: the flower
  would stay onscreen >much longer than the shoe. But Eagleman insisted
  that all the pictures appeared for the same length of time. The only
  difference was the degree of attention that I paid to them. The shoe,
  by its third or fourth >appearance, barely made an impression. The
  flower, more rare, lingered and blossomed, like those childhood
  summers.
#+END_QUOTE

As we age, this process comes into play even more, making time seem to
fly by much faster. This is because the more we age, the more often we
come into contact with information our brains have already processed.
This familiar information takes a shortcut through our brains, giving us
the feeling that time is speeding up and passing us by.

** How to make our days longer
   :PROPERTIES:
   :CUSTOM_ID: how-to-make-our-days-longer
   :END:

Learning about the brain is always fascinating, but it's even better
when you can put that learning into practice. That's why I love this
idea of [[file:20200724212844-time_perception.org][Time perception]] so
much---we can use it to our advantage fairly easily.

According to the research, if we feed our brains more new information,
the extra processing time required will make us feel like time is moving
more slowly. And supposing it's true that perception is reality, we'd
effectively be making our days longer. How awesome is that?

Here are five ways you could put this into practice immediately. If you
have more ideas, I'd love to hear them!

1. Keep Learning
2. Visit new places
3. Meet new people
4. Try new activities
5. Be Spontaneous
