* The Art of War - A summary of the book

** Lesson 1: Only enter battles you know you can win:

- Winners know when to fight and when not to fight. Losers always fight
  and thus often end up losing.
- Fools enter battles and then start thinking about how to win.
  Strategists know how they're going to win before they even start to battle.

Have you ever thought about the fact that the most skillful fighters often avoid
battles and that that's why they're never defeated? Take Bobby Fischer, for
instance. The most brilliant chess player of all time instantly retreated, after
he won the world championship, not playing again for 20 years.

So if you're starting a business, look at the industry first. Can you even win
against your biggest competitors? And if not, is there a different niche you can
fill?

Creating a soda brand to compete with Coca-Cola would certainly be an effort in
vain, given that over 1 billion drinks of the brand are consumed every single
day. But maybe you can create a higher-priced, eco-friendly alternative, that
targets single mums. That could make a fortune!

#+BEGIN_QUOTE
  *NOTE:* Only enter battles you know you can win.
#+END_QUOTE

** Lesson 2: Deceive your competitors to impose your will on them.

#+BEGIN_QUOTE
Mask strength with weakness, courage with timidity and order with disorder,
Sun Tzu says.
#+END_QUOTE

- A clever army will win not with their bodies, but with their minds.
- Making it seem like you're miles away when you're close to the enemies
  base with distractions, or surprise attacking in several places to splinter
  opposing forces are common tactics in the battlefield.
- They're based on deceit and supposed to make your enemy do what you
  want them to do.

In business, you can do the same. I'm always baffled to discover insanely
profitable and dominating businesses, which, on the front-end, appear like
they're a mom-and-pop store. Take Appsumo, for example.  There's not much to
discover, it seems like a small daily deal site, right?

Here's the kicker: Appsumo is an 8-figure business. If you have to count, that's
north of $10 million/year. They have over 1 million email subscribers and made
$1 million in their first year (2010). There are endless examples like this one
on the web, and this humbleness and modesty are a great way to throw off
competitors -- even if they might be your default setting, like Noah's, who's
the founder.

** Lesson 3: Lead your team as if you were leading a single man by thehand.
Eventually, your business will need a team. And eventually, that team will have
to grow. But as companies get bigger, they get more complex.

Every single human adds an infinite amount of feelings, thoughts and ideas to
the business, and all of those have to be managed.

#+BEGIN_QUOTE
"A skilled general leads his army, as if he was leading a single man by the
hand." Sun Tzu
#+END_QUOTE

Whether you're managing a big army or a small one, the tools are the same: Break
them down into smaller groups and then use clear signals to steer them into the
right direction.

- In business, that means teams should stay small, 3-4 people are often
  a good number to cooperate, before things get too complicated.
- Then you can set clear signals, like sales targets, tools to use, and
  a daily morning briefing, to make sure everyone's on track.
- Never forget 1-on-1 interaction with everyone on your team, because if
  you treat your employees like family, they'll be just as loyal.
