#+title: Woods Thress Steps to Forming New Habits
#+author: nicholas martin
#+email: nmartin84@gmail.com

+ author :: Ali Pattillo
+ tags :: [[file:../psychology/202101242150-habits.org][habits]]
+ source :: https://www.inverse.com/mind-body/the-truth-about-making-breaking-habits?utm_source=pocket-newtab

#+begin_quote
We think if we're motivated enough and have enough self-control, we'll
follow through without realizing that the circumstances around us, the
contexts that we're living in, have a huge impact on how easy something
is and how often we can repeat it.
#+end_quote

* Ease Up
   :PROPERTIES:
   :CUSTOM_ID: ease-up
   :END:

If something's too difficult, you simply won't do it, Wood says.
Depending on your goal, fill your pantry with healthy snacks, turn off
your social media notification, or sign up for a gym near your office.
Make the choice to "do better" easier.

* Make it enjoyable
   :PROPERTIES:
   :CUSTOM_ID: make-it-enjoyable
   :END:

You're not going to repeat a behavior that you don't enjoy, Wood says.
And you're not going to form a habit for something that you just hate.
So even if you've chosen an unappealing habit, find a way to make it
fun. Maybe that means stopping by a favorite smoothie bar after a
morning run or watching trash TV while you complete a dreaded task.

* Repeat on a regular basis
   :PROPERTIES:
   :CUSTOM_ID: repeat-on-a-regular-basis
   :END:

On average, based on the research, it takes about 66 days to make a
simple health change. The more complex behavior, the longer it might
take. Generally, two months is a good "ballpark estimate" for the
average person to form or break a habit, Wood says. And if you miss a
day, no need to panic. Habit memory takes a long time to form, but
luckily, a single skip doesn't wipe away what's been built up in the
past.
