#+title: Fundamentals of Machine Learning - Intro to SciKit Learn
#+author: Nick Martin
#+email: nmartin84@gmail.com
#+created: [2021-01-20 22:27]

* Introduction

Machine learning models can learn by example. Algorithms learn rules from
example data. A set of labeled examples used for learning called [[[[file:~/projects/orgmode/programming/202101212124-training_data.org][training
data]]]].

The learned rules should also be able to generalize to correctly recognize or
predict new examples not in the original [[[[file:~/projects/orgmode/programming/202101212124-training_data.org][training data]]]].

So to conclude on this, it's good to understand that machine learning draws heavily
on [[[[file:~/projects/orgmode/statistics/202101212128-statistics.org][statistics]]]] (estimate reliability of predictions, infer conclusions of
data), in addition to [[[[file:~/projects/orgmode/programming/202101212129-computer_science.org][computer science]]]] for (large-scale computing,
algorithms to capture, manipulate, index, combine, retrieve and perform
predictions on data).

** Key Concepts in Machine Learning

There are essentially two types of machine learning:
- Supervised machine learning, or supervised learning.
  + Learn to predicted target values from labelled data
  + classification (target values are discrete classes)
  + regression (target values are continuous values)

#+begin_quote
"So if the output is a category a finite number of possibilities such as a
fraudulent or not fraudulent prediction for a credit card transaction. Or maybe
it's the English word associated with an audio signal for speech recognition. We
call this a classification problem within [[[[file:../../fleeting/202101232318-supervised_learning.org][supervised learning]]]], and the
function that we learn is called the classifier."
#+end_quote

If the output variable we want to predict is not a category, but a real valued
number like the amount of time in seconds it would likely take a car to
accelerate from 0 to 100 kilometers per hour. We call that regression problem.
And we're learning something called a regression function. More formally we
typically denote a table of data items using capital letter X and there's one
data item per row. And the labels that we associate with each item are stored in
the variable y. And our goal is to learn some function that maps data item in X
to a label in Y.
